### PR TITLE
Fix of the Fix Movie details shows old schedules issue #12

### LINKED ISSUE #12: Movie details shows old schedules
### Description:
When opening a movie detail, we'll see all schedules – even the ones from 7+ days ago.

### PR DESCRIPTION
**Pull request by Pedro-Revez-Silva**
### Description:
Added a filter to remove Movie schedules older than 7 days from the Movie details.
@pdrbrnd  Helped me a lot on this issue.

#### Issues:
Closes #12

Esta contribuição foi realizada para o Challenge devPT # 1. Discord username: Not#5071

### CODE REVIEW

**Comment by Pedro-Revez-Silva** [comment]
@pdrbrnd Desculpa a demora. Parti o meu projecto local todo e achei melhor fazer reset. Só estão aqui as alterações que deviam.

**Comment by pdrbrnd** [comment]
@Pedro-Revez-Silva did you install the dependencies when you did this fresh install?
The build is failing due to wrong formatting (prettier)

**Comment by Pedro-Revez-Silva** [comment]
@pdrbrnd I installed the dependencies and ran the `npm run dev` command with no issues. For some reason I didn't get a warning before but there is an issue with the identation.

**Comment by Pedro-Revez-Silva** [comment]
Tried to fix automagically on local branch, but I get an error when trying to push into remote. Lets see if it passes now.

**Comment by pdrbrnd** [comment]
@Pedro-Revez-Silva nice work. deploying 🚀

**Pull request merged**
